# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushDataV3ApiWrapper.proto
# Protobuf Python Version: 4.25.3
# MODIFIED: Added error handling for descriptor pool conflicts
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




# Handle descriptor pool conflicts gracefully
try:
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aPushDataV3ApiWrapper.proto\x12\x04spot\"\xea\x01\n\x14PublicIncreaseDepths\x12\x33\n\x04\x61sks\x18\x01 \x03(\x0b\x32%.spot.PublicIncreaseDepths.PriceLevel\x12\x33\n\x04\x62ids\x18\x02 \x03(\x0b\x32%.spot.PublicIncreaseDepths.PriceLevel\x12\x11\n\teventtype\x18\x03 \x01(\t\x12\x13\n\x0b\x66romVersion\x18\x04 \x01(\t\x12\x11\n\ttoVersion\x18\x05 \x01(\t\x1a-\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\t\"\x83\x01\n\x14PushDataV3ApiWrapper\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08sendTime\x18\x03 \x01(\x03\x12\x38\n\x14publicIncreaseDepths\x18\x04 \x01(\x0b\x32\x1a.spot.PublicIncreaseDepthsB:\n\x1d\x63om.mexc.api.spot.model.ws.pbB\x19PushDataV3ApiWrapperProtob\x06proto3')
except TypeError as e:
    # Handle "duplicate file name" error - file already in descriptor pool
    if "duplicate file name" in str(e) or "Couldn't build proto file" in str(e):
        try:
            # Try to find existing descriptor
            DESCRIPTOR = _descriptor_pool.Default().FindFileByName('PushDataV3ApiWrapper.proto')
        except KeyError:
            # If not found, create a new pool
            import logging
            logging.warning("Protobuf descriptor pool conflict - creating workaround")
            DESCRIPTOR = None
    else:
        raise

# Only build if DESCRIPTOR is valid
if DESCRIPTOR is not None:
    _globals = globals()
    _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PushDataV3ApiWrapper_pb2', _globals)
    if _descriptor._USE_C_DESCRIPTORS == False:
      _globals['DESCRIPTOR']._options = None
      _globals['DESCRIPTOR']._serialized_options = b'\n\035com.mexc.api.spot.model.ws.pbB\x19PushDataV3ApiWrapperProto'
      _globals['_PUBLICINCREASEDEPTHS']._serialized_start=37
      _globals['_PUBLICINCREASEDEPTHS']._serialized_end=271
      _globals['_PUBLICINCREASEDEPTHS_PRICELEVEL']._serialized_start=226
      _globals['_PUBLICINCREASEDEPTHS_PRICELEVEL']._serialized_end=271
      _globals['_PUSHDATAV3APIWRAPPER']._serialized_start=274
      _globals['_PUSHDATAV3APIWRAPPER']._serialized_end=405
else:
    # Fallback: manually define message classes if descriptor failed
    import logging
    logging.error("Failed to load protobuf descriptor - protobuf functionality will be limited")
    # Define minimal classes to prevent import errors
    class PushDataV3ApiWrapper:
        def __init__(self):
            self.channel = ""
            self.symbol = ""
            self.sendTime = 0
            self.publicIncreaseDepths = None
        
        def ParseFromString(self, data):
            raise NotImplementedError("Protobuf descriptor not available")
        
        def HasField(self, field):
            return False
    
    class PublicIncreaseDepths:
        def __init__(self):
            self.asks = []
            self.bids = []
            self.eventtype = ""
            self.fromVersion = ""
            self.toVersion = ""
    
    _globals = globals()
    _globals['PushDataV3ApiWrapper'] = PushDataV3ApiWrapper
    _globals['PublicIncreaseDepths'] = PublicIncreaseDepths

# @@protoc_insertion_point(module_scope)

